### ISSUE TITLE
Scramble the display order of answer options

### ISSUE THREAD

**Issue by rachelktyjohnson** [rachelktyjohnson/hktbf22-quiz-app#2]
# This is too easy!

**You must be assigned this issue in order for your Pull Request to be accepted and merged. Please refer to "How to claim an Issue here: https://github.com/rachelktyjohnson/hktbf22-quiz-app/blob/master/CONTRIBUTING.md#how-to-claim-an-issue**

You may have noticed by now that the correct answer is always displayed first. That's no good! Your task is to shuffle the order in which the answers appear on the grid. 

There are a few ways to do this, but our recommendation is to do this within the `addQuestionToDisplay()` method in `question.js`

**You must not change the data structure of `data.js`.**

**Comment by Lyndsayfutrell** [comment]
Okay I think I will give this one a go. Slack handle Lyndsay Futrell. FSJS tech degree 🤓

**Comment by rachelktyjohnson** [comment]
@Lyndsayfutrell all yours!

**Comment by S-ahil-Saxen-a** [comment]
Hey @rachelktyjohnson , I have made this type of feature before, so please assign it to me also under hacktoberfest'22

**Comment by fauxriarty** [comment]
Hey! I'd love to work on this if it's still open.

**Comment by fauxriarty** [comment]
I just forked the repo and went through the code, it already randomizes the order of options displayed  so theres nothing left for me to do, unless you have a suggestion (for hacktoberfest haha)

**Comment by rachelktyjohnson** [comment]
@fauxriarty oh dear my apologies! I must have missed this last year 🙈

You're welcome to have a look at issue#1 as anyone can add to that one! Otherwise I'm more than happy to see what additions/fixes you come up with 😁

**Comment by fauxriarty** [comment]
Hey I made a PR with a few changes. Check and let me know what you think :)

**Comment by rachelktyjohnson** [comment]
@fauxriarty just merged it! Although it looks like there might be a bug now

**Comment by rachelktyjohnson** [comment]
@fauxriarty might be able to get another PR in ;)
