### ISSUE TITLE
Enable/Disable "Next" button where appropriate

### ISSUE THREAD

**Issue by rachelktyjohnson** [rachelktyjohnson/hktbf22-quiz-app#3]
# You can't skip questions!

**You must be assigned this issue in order for your Pull Request to be accepted and merged. Please refer to "How to claim an Issue here: https://github.com/rachelktyjohnson/hktbf22-quiz-app/blob/master/CONTRIBUTING.md#how-to-claim-an-issue**

Oh dear, it looks like the "Next" button allows quiz-takers to move to the next question before answering the current one! We can't have that. Your task for this issue is to:

1. Disable the "Next" button if an answer hasn't been selected
2. Enable the "Next" button when an answer has been selected and users can move forward
3. Disable the "Next" button once again when the next question loads

There are many ways to do this, but our suggestion is to focus only on the `question.js` file.

**Comment by NiiVx** [comment]
Hello, @rachelktyjohnson, nice to meet you! I would like to contribute, could you assign me this issue ?

**Comment by rachelktyjohnson** [comment]
> Hello, @rachelktyjohnson, nice to meet you! I would like to contribute, could you assign me this issue ?

Hi @NiiVx please refer to `contributing.md` for how to claim an issue and make contributions as a TD student!

**Comment by NiiVx** [comment]
Ohhh @rachelktyjohnson, so sorry, I didn't see that the repository was exclusive to TD students.

**Comment by jajablinky** [comment]
i would like to do this one :)
