### ISSUE TITLE
Disable answers between questions

### ISSUE THREAD

**Issue by rachelktyjohnson** [rachelktyjohnson/hktbf22-quiz-app#5]
# Select ALL the answers!

**You must be assigned this issue in order for your Pull Request to be accepted and merged. Please refer to "How to claim an Issue here: https://github.com/rachelktyjohnson/hktbf22-quiz-app/blob/master/CONTRIBUTING.md#how-to-claim-an-issue**

Currently, a user can keep answering the same question with different (or the same) answer buttons. We can't have that! Your task is to make sure all answer buttons are disabled once one has been picked. Then, make sure they are enabled again when the next question is loads!

This functionality should be triggered in `handleInteraction()` in `game.js`, but the logic should live in `question.js`

**Comment by OluwaDraco** [comment]
I would like to be assigned this Issue. My Slack handle is Olushola Oludipe and I'm in the web development TechDegree. Thank you!

**Comment by rachelktyjohnson** [comment]
> I would like to be assigned this Issue. My Slack handle is Olushola Oludipe and I'm in the web development TechDegree. Thank you!

@OluwaDraco all yours!
