### ISSUE TITLE
Change colors based on question category

### ISSUE THREAD

**Issue by rachelktyjohnson** [rachelktyjohnson/hktbf22-quiz-app#6]
# Let's get colorful

**You must be assigned this issue in order for your Pull Request to be accepted and merged. Please refer to "How to claim an Issue here: https://github.com/rachelktyjohnson/hktbf22-quiz-app/blob/master/CONTRIBUTING.md#how-to-claim-an-issue**

Currently the background and buttons are a very nice shade of blue, but let's mix it up a little! Your task is to change the background and button colors based on the category of the question. These should all change when a new question is loaded. Be sure to check the data structure of our data in `data.js`.

**Please follow this color scheme:**
**html**: #3659a2
**css**: #4a4290
**javascript**: #0e8397
**for any other category**: #9f4b84;

**Comment by chiragcode11** [comment]
can you assign this to me?

**Comment by rachelktyjohnson** [comment]
> can you assign this to me?

@chiragcode11 please refer to `contributing.md` for instructions on how to request an issue!

**Comment by Sparsh47** [comment]
Can you assign this issue to me? I know how to do this and am willing to work on this issue.

**Comment by rachelktyjohnson** [comment]
> Can you assign this issue to me? I know how to do this and am willing to work on this issue.

Hi Sparsh, please refer to contributing.md on how to request issues!

**Comment by TravisAlstrand** [comment]
Heyooo! I would be happy to be assigned this one if you think nobody is going to want it from here on out. It's been a while. :)

**Comment by rachelktyjohnson** [comment]
@TravisAlstrand all yours!
